/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcMapLegend {
    /**
    * Colors of the legends
    */
    'colors': any;
    /**
    * Counts of the legends
    */
    'counts': any;
    /**
    * Disable the tooltip
    */
    'disableTooltip': boolean;
    'icons': any;
    /**
    * Description of the legend tooltip
    */
    'legendText': string;
    /**
    * The name list of legends
    */
    'names': any;
    /**
    * Title of the legends
    */
    'titleText': string;
    /**
    * Customize the svg style completely
    */
    'tooltipProps': any;
  }
}

declare global {


  interface HTMLPwcMapLegendElement extends Components.PwcMapLegend, HTMLStencilElement {}
  var HTMLPwcMapLegendElement: {
    prototype: HTMLPwcMapLegendElement;
    new (): HTMLPwcMapLegendElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-map-legend': HTMLPwcMapLegendElement;
  }
}

declare namespace LocalJSX {
  interface PwcMapLegend {
    /**
    * Colors of the legends
    */
    'colors'?: any;
    /**
    * Counts of the legends
    */
    'counts'?: any;
    /**
    * Disable the tooltip
    */
    'disableTooltip'?: boolean;
    'icons'?: any;
    /**
    * Description of the legend tooltip
    */
    'legendText'?: string;
    /**
    * The name list of legends
    */
    'names'?: any;
    /**
    * Title of the legends
    */
    'titleText'?: string;
    /**
    * Customize the svg style completely
    */
    'tooltipProps'?: any;
  }

  interface IntrinsicElements {
    'pwc-map-legend': PwcMapLegend;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-map-legend': LocalJSX.PwcMapLegend & JSXBase.HTMLAttributes<HTMLPwcMapLegendElement>;
    }
  }
}


