/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcMapLegend {
    /**
    * Colors of the legends
    */
    'colors': string;
    /**
    * Counts of the legends
    */
    'counts': string;
    /**
    * Disable the tooltip
    */
    'disableTooltip': boolean;
    /**
    * Description of the legend tooltip
    */
    'legendText': string;
    /**
    * The name list of legends
    */
    'names': string;
    /**
    * Title of the legends
    */
    'titleText': string;
  }
}

declare global {


  interface HTMLPwcMapLegendElement extends Components.PwcMapLegend, HTMLStencilElement {}
  var HTMLPwcMapLegendElement: {
    prototype: HTMLPwcMapLegendElement;
    new (): HTMLPwcMapLegendElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-map-legend': HTMLPwcMapLegendElement;
  }
}

declare namespace LocalJSX {
  interface PwcMapLegend {
    /**
    * Colors of the legends
    */
    'colors'?: string;
    /**
    * Counts of the legends
    */
    'counts'?: string;
    /**
    * Disable the tooltip
    */
    'disableTooltip'?: boolean;
    /**
    * Description of the legend tooltip
    */
    'legendText'?: string;
    /**
    * The name list of legends
    */
    'names'?: string;
    /**
    * Title of the legends
    */
    'titleText'?: string;
  }

  interface IntrinsicElements {
    'pwc-map-legend': PwcMapLegend;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-map-legend': LocalJSX.PwcMapLegend & JSXBase.HTMLAttributes<HTMLPwcMapLegendElement>;
    }
  }
}


